# general settings
name: LapSRNV4.13_Celeb26k_BS32_L1_400k_V100_oneface_11face
model_type: FSRModel
scale: 8
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: celeba
    type: BFSRDataset_onefaceb
    dataroot_gt: ./datasets/data/train/celeb128
    dataroot_lq16: ./datasets/data/train/celeb16
    dataroot_lq32: ./datasets/data/train/celeb32
    dataroot_lq64: ./datasets/data/train/celeb64
    faceb_gt: ./datasets/data/face_boundary
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 10
    prefetch_mode: ~
  val:
    name: celeba_val
    type: PairedImageDataset
    dataroot_gt: ./datasets/data/test/celeb128
    dataroot_lq: ./datasets/data/test/celeb16
    io_backend:
      type: disk

# network structures
network_g:
  type: LapSrnMSV4_13
  num_out_ch: 3
  dim : 64
  fb_single_face : true
# path
path:
  pretrain_network_g: experiments/LapSRNV4.10_Celeb26k_BS64_L1_600k_V100/models/net_g_600000.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [400000]
    restart_weights: [1]
    eta_min: !!float 1e-7


  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  mse_opt:
    type: MSELoss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 2e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: false
  # wandb:
  #   project: ~
  #   resume_id: ~
  #   entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
# cd BasicSR
# CUDA_VISIBLE_DEVICES=1 nohup python -u basicsr/train.py -opt options/train/FSR/train_LapSRNV4.1_x8.yml > runlog/train_LapSRNV4.1_x8.log 2>&1 &

# ps -ef | grep  train_LapSRNV4.13 | grep -v grep | awk '{print $2}' | xargs kill -9

