# general settings
name: BSRFSR_Celeb30_BS1_L1_50k_V100
model_type: FSRModel
scale: 8
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: celeba
    type: FSRDataset # dataset no face(NO LPE)
    dataroot_gt: ./datasets/data/inferencec/HR
    dataroot_lq16: ./datasets/data/inferencec/LR
    dataroot_lq32: ./datasets/data/train/celeb32
    dataroot_lq64: ./datasets/data/train/celeb64
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 10
    prefetch_mode: ~
  val:
    name: celeba_val
    type: PairedImageDataset
    dataroot_gt: ./datasets/data/inferencec/HR
    dataroot_lq: ./datasets/data/inferencec/LR
    io_backend:
      type: disk
  # val_2:
  #   name: DF2kVAL
  #   type: PairedImageDataset
  #   dataroot_gt: ./datasets/DF2K_val/GTmod4
  #   dataroot_lq: ./datasets/DF2K_val/LRbicx4
  #   io_backend:
  #     type: disk

# network structures
network_g:
  type: BSRFSR
  num_out_ch: 3
  conv : BSConvU
# path
path:
  pretrain_network_g: experiments/BSRFSR(no_rep)_Celeb26k_BS64_L1_300k_V100/models/net_g_latest.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-5
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [50000]
    restart_weights: [1]
    eta_min: !!float 1e-7


  total_iter: 50000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: True
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: True
# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: false
  # wandb:
  #   project: ~
  #   resume_id: ~
  #   entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
# cd BasicSR
# CUDA_VISIBLE_DEVICES=1 nohup python -u basicsr/train.py -opt options/train/FSR/train_LapSRNV4.1_x8.yml > runlog/train_LapSRNV4.1_x8.log 2>&1 &

# CUDA_VISIBLE_DEVICES=0,1 \
# nohup python -m torch.distributed.launch --nproc_per_node=2 --master_port=25322 \
# basicsr/train.py -opt options/train/FSR/train_LapSRNV4.10_x8.yml --launcher pytorch > runlog/train_LapSRNV4.10_600k_T4_2.log 2>&1 &

# ps -ef | grep  train_BSRFSR.yml | grep -v grep | awk '{print $2}' | xargs kill -9

