# general settings
name: RLFN_DF2Kx4_F48M48_G192BS16_L1_600k
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
#    dataroot_gt: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_HR_sub
#    dataroot_lq: /mnt/yxsun/Project/Data/datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
#    (for lmdb)
    dataroot_gt: ./datasets/DF2K/GTmod4
    dataroot_lq: ./datasets/DF2K/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 20
    prefetch_mode: ~
  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ./datasets/Set5/GTmod12
    dataroot_lq: ./datasets/Set5/LRbicx4
    io_backend:
      type: disk
  val_2:
    name: DF2kVAL
    type: PairedImageDataset
    dataroot_gt: ./datasets/DF2K_val/GTmod4
    dataroot_lq: ./datasets/DF2K_val/LRbicx4
    io_backend:
      type: disk

# network structures
network_g:
  type: RLFN
  in_channels: 3
  out_channels: 3
  feature_channels: 48
  mid_channels: 48
  upscale_factor: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]
    restart_weights: [1]
    eta_min: !!float 1e-7


  total_iter: 600000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e5
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: false
  # wandb:
  #   project: ~
  #   resume_id: ~
  #   entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
# CUDA_VISIBLE_DEVICES=0 nohup python -u basicsr/train.py -opt options/train/train_RLFN_x4.yml > norunlog.log 2>&1 &
# ps -ef | grep RLFN | grep -v grep | awk '{print $2}' | xargs kill -9
# bs64 :2023-04-24 18:28:24,101 INFO: [RFLN_..][epoch:  0, iter:     200, lr:(1.000e-03,)] [eta: 18 days, 6:19:41, time (data): 2.847 (2.777)] l_pix: 4.3985e-02